basic_settings:
  site_title: Zephir Language Blog
  site_tagline: The official blog of Zephir Language
  favicon_image: /images/favicon.png
  site_description: 'The official blog of Zephir Language'
  site_keywords: 'php, phalcon, zephir, language, php modules'
  site_baseurl: 

header_settings:
  logo_image: 
  logo_width: 200
  overlay_opacity: 0.7

menu_settings:
  menu_items:
    - title: 'Latest'
      url: '/'
    - title: 'About'
      url: '/about'
    - title: 'Zephir site'
      url: 'https://zephir-lang.com/en'
    - title: 'Documentation'
      url: 'https://docs.zephir-lang.com/'
    - title: 'Discussions'
      url: 'https://github.com/zephir-lang/zephir/discussions'

grid_settings:
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/your@email.com'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: 'https://www.facebook.com/groups/zephir.language/'
  twitter_url: 'https://twitter.com/zephirlang'
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: 'https://github.com/zephir-lang/zephir'
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''
  disqus_tag: ''
  discord_url: 'https://phalcon.io/discord'

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#F5F7FA'
  text_dark_color: '#2A2F36'
  text_medium_color: '#4C5561'
  text_light_color: '#677979'
  accent_color: '#2E8470'
  border_color: '#dddddd'
  overlay_background_color: '#161B21'
  overlay_text_color: '#ffffff'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Merriweather:400,700&display=swap" rel="stylesheet">'
  title_font: '"Merriweather", sans-serif'
  body_font: '"Muli", sans-serif'
  regular_weight: 400
  bold_weight: 700
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 400
    letter_spacing: 0
  site_tagline:
    small_size: 16
    medium_size: 17
    large_size: 18
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 30
    medium_size: 17
    large_size: 18
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 400
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: false
  analytics_code: ""
  custom_styles: ""
  header_js: "<script src='https://identity.netlify.com/v1/netlify-identity-widget.js'></script>"
  footer_js: ""
